### ISSUE TITLE
OpenBSD seems broken

### ISSUE THREAD

**Issue by sahlberg** [cross-platform-actions/openbsd-builder#11]
Downloading disk image: https://github.com/cross-platform-actions/openbsd-builder/releases/download/v0.2.0/openbsd-7.1-x86-64.qcow2

This image does not exist.

**Comment by jacob-carlborg** [comment]
Support for 7.1 was added in OpenBSD builder 0.3.0. If you're action is trying to access version 0.2.0 of OpenBSD builder it means you're using an old version of the action. Support for OpenBSD 7.1 was added in version 0.6.0 of the GitHub action (https://github.com/cross-platform-actions/action/releases/tag/v0.6.0).

**Comment by sahlberg** [comment]
I tried to use it like this:

  BSDs:
    runs-on: macos-latest

    strategy:
      matrix:
        os:
          - name: OpenBSD
            version: 7.1
            pkginstall: pkg_add cmake

    name: ${{ matrix.os.name }} ${{ matrix.os.version }}

    steps:
      - uses: actions/checkout@main

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.3.1
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            mkdir build
            cmake -B build
            cd build
            make
            sudo make install

And here is how it fails:

Run cross-platform-actions/action@v0.3.1
  
Downloading disk image: https://github.com/cross-platform-actions/openbsd-builder/releases/download/v0.2.0/openbsd-7.1-x86-64.qcow2
Downloading hypervisor: https://github.com/cross-platform-actions/resources/releases/download/v0.3.1/xhyve-macos.tar
Downloading resources: https://github.com/cross-platform-actions/resources/releases/download/v0.3.1/resources-macos.tar
/usr/bin/ssh-keygen -t ed25519 -f /tmp/resourcesZXaz7u/id_ed25519 -q -N 
/usr/sbin/mkfile -n 40m /tmp/resourcesZXaz7u/res.raw
Error: Unexpected HTTP response: 4044

That first link to the qcow2 image does not exist.

**Comment by sahlberg** [comment]
It seems to work with cross-platform-actions as 0.6.0

**Comment by jacob-carlborg** [comment]
FYI 0.6.2 is the latest version.
