### ISSUE TITLE
Support 7.4.

### ISSUE THREAD

**Issue by hyoklee** [cross-platform-actions/openbsd-builder#15]
The current release is [OpenBSD 7.4](https://www.openbsd.org/74.html), released October 16, 2023.

**Comment by hyoklee** [comment]
@jacob-carlborg, Thanks for fixing it quickly.

However, I get 404 error for arm64 in my 7.4 test action: 

 https://github.com/cross-platform-actions/openbsd-builder/releases/download/v0.6.0/openbsd-7.4-arm64.qcow2

**Comment by jacob-carlborg** [comment]
You need to update to version 0.21.0 of the action which I just released. The action is split across several repository. The necessary changes for this repository was complete and therefore this issue was closed. But I still had to do some minor things in the main repository.
